# Configurazione dei casi d'uso
settings:
  # Percorso dove creare i file (relativo allo script)
  output_dir: "content/chapters/3_requirements/requirement/requisiti-vincolo/requisiti-obbligatori/content/req-list"

  # Nome del file aggregatore (se lasciato vuoto, non lo crea)
  index_file: "requisiti-vincolo-obbligatori-list.typ"

  # Il prefisso non può contenere il carattere di title separator
  prefix: "RCM"
  # Estensione dei file generati
  extension: ".typ"

  # Regole di numerazione e stile
  formatting:
    padding: 2 # Zeri iniziali: 2 -> "01", 3 -> "001"
    separator: "." # Separatore numeri: "1.1" vs "1-1"
    title_separator: "_" # Separatore tra numero e titolo: "01_Titolo"
    filename_style: "snake_case" # "snake_case" (a_b) o "kebab_case" (a-b)


  index_header_template: "content/chapters/3_requirements/requirement/requisiti-vincolo/requisiti-obbligatori/content/deps/index_header_template.typ"
  index_row_template: "content/chapters/3_requirements/requirement/requisiti-vincolo/requisiti-obbligatori/content/deps/index_row_template.typ"
  index_footer_template: "content/chapters/3_requirements/requirement/requisiti-vincolo/requisiti-obbligatori/content/deps/index_footer_template.typ"

  # (Opzionale) File template da copiare per i nuovi file
  template_path: "content/chapters/3_requirements/requirement/requisiti-vincolo/requisiti-obbligatori/content/deps/template.typ"

# La struttura gerarchica
structure:
    - Utilizzo python
    - Utilizzo fastapi
    - Utilizzo embedder remoto
    - Utilizzo di PostgreSQL
    - Utilizzo di grafana
    - Rispetto modello dati HDA
    - Alta configurabilità del sistema
    - Realizzazione ricerche similarità
    # - Benchmark base
    - Ricerca full text ottimizzata su lingua
    - Ricerca linked
    - Roundtrip unico per le ricerche
    - Ingestion
    - specifiche sistema di test
