# Configurazione dei casi d'uso
settings:
  # Percorso dove creare i file (relativo allo script)
  output_dir: "content/chapters/3_requirements/requirement/requisiti-vincolo/requisiti-desiderabili/content/req-list"

  # Nome del file aggregatore (se lasciato vuoto, non lo crea)
  index_file: "requisiti-vincolo-desiderabili-list.typ"

  # Il prefisso non può contenere il carattere di title separator
  prefix: "RCD"
  # Estensione dei file generati
  extension: ".typ"

  # Regole di numerazione e stile
  formatting:
    padding: 2 # Zeri iniziali: 2 -> "01", 3 -> "001"
    separator: "." # Separatore numeri: "1.1" vs "1-1"
    title_separator: "_" # Separatore tra numero e titolo: "01_Titolo"
    filename_style: "snake_case" # "snake_case" (a_b) o "kebab_case" (a-b)


  index_header_template: "content/chapters/3_requirements/requirement/requisiti-vincolo/requisiti-desiderabili/content/deps/index_header_template.typ"
  index_row_template: "content/chapters/3_requirements/requirement/requisiti-vincolo/requisiti-desiderabili/content/deps/index_row_template.typ"
  index_footer_template: "content/chapters/3_requirements/requirement/requisiti-vincolo/requisiti-desiderabili/content/deps/index_footer_template.typ"

  # (Opzionale) File template da copiare per i nuovi file
  template_path: "content/chapters/3_requirements/requirement/requisiti-vincolo/requisiti-desiderabili/content/deps/template.typ"

# La struttura gerarchica
structure:
    - Uso kubernetes
    - Non ordine dei dati in ingestion
    - Benchmark avanzati
